const REQUEST = {
  login: '/user/login',
  get_code_img: '/user/get_code_img',
  index: '/',
  order_week_data: '/order/order_week_data', //近7天订单数
  user_list: '/user/get_user_list',
  address_list: '/user/get_user_addressList',
  orderList: '/order/orderList',
  categoryList: '/goods/categoryList',
  updateGoodsInfo: '/goods/updateGoodsInfo',
  addCategory: '/category/addCategory',
  deleteCategory: '/category/deleteCategory',
  updateCateGory: '/category/updateCateGory',
  getSkuList: "/goods/getSkuList",
  changeSku: "/goods/changeSku",
  addVertifyRecord: '/goods/addVertifyRecord',
  goodsList: '/goods/goodsList',
  addGoods: '/goods/addGoods',
  updateGoods: '/goods/updateGoods',
  goodsAttributeCategoryList: '/category/goodsAttributeCategoryList',
  addGoodsAttributeCategory: '/category/addGoodsAttributeCategory',
  updateGoodsAttributeCategory: '/category/updateGoodsAttributeCategory',
  deleteGoodsAttributeCategory: '/category/deleteGoodsAttributeCategory',
  addUpdateGoodsAttribute: '/category/addUpdateGoodsAttribute',
  GoodsAttributeList: '/category/GoodsAttributeList',
  GoodsAttributeInfo: '/category/GoodsAttributeInfo',
  deleteGoodsAttribute: '/categary/deleteGoodsAttribute',
  getCategoryTree: '/categary/getCategoryTree',
  getSTS: '/getSTS',
  upload: '/upload',
  changeGoodsStatus: '/goods/changeGoodsStatus',
  addComment: '/order/addComment', //添加评论
  CommerList: '/order/CommerList',
  addRemark: '/order/addRemark',
  diverGoods: '/order/diverGoods',
  getMessageList: '/message/getMessageList',
  changeMessageStatus: '/message/changeMessageStatus',
  getFlashList: '/flash/getFlashList',
  crateFlashPromotion: '/flash/crateFlashPromotion',
  delFlashPromotion: '/flash/delFlashPromotion',
  getFlashPromotionGoodsList: '/flash/getFlashPromotionGoodsList',
  crateFlashPromotionGoods: '/flash/crateFlashPromotionGoods',
  delFlashPromotionGoods: '/flash/delFlashPromotionGoods',
  updateFlashPromotionGoods: '/flash/updateFlashPromotionGoods'
};
export default REQUEST;
